### ISSUE TITLE
adding other languages

### ISSUE THREAD

**Issue by andy5995** [RazorSh4rk/random-word-api#13]
I was wondering if you'd be able to add other languages to your word generator, such as German and Dutch? (?lang=DE)...

**Comment by RazorSh4rk** [comment]
I mean i could try making other collections, the issue is, i have limited proficiency in German and Japanese, other than that i don't speak other languages, and i can't check if those list contain anything inappropriate. I will try setting up a way for contributors to add more languages without having to touch the code :)

**Comment by andy5995** [comment]
Sounds like a plan, thank you. I'm using your api for my [aawordsearch](https://github.com/theimpossibleastronaut/aawordsearch) project, btw.

**Comment by RazorSh4rk** [comment]
Added support for other languages. It takes me 4-5h to translate every word so i will release the script i used for converting after i clean it up a bit :)

**Comment by andy5995** [comment]
Thanks @RazorSh4rk

**Comment by ManuSquall** [comment]
Hello world, thanks you @RazorSh4rk  for making this api available, I would like to be able to contribute to also add the French language, is it possible?
