### ISSUE TITLE
so i may have taken down the entire site

### ISSUE THREAD

**Issue by sudocode1** [RazorSh4rk/random-word-api#5]
ok so im not sure i should report this here or not but

i requested `/all` and it crashed the site completely
even `/home` isnt working. you should probably look into this

have a nice day:)

**Comment by Sukadia** [comment]
haha, so it was you! i was worried because my discord bot relies on this api so it hasn't been able to select new random words to whitelist. glad it didn't just get closed with no warning

**Comment by sudocode1** [comment]
omg im so sorry!! i was trying it out for my [https://github.com/sudocode1/waffl](waffl) project to see if i could just get an array of words and randomly select from them. im really sorry for any trouble i caused :^)

(also we should talk sometime, roux#3300)

**Comment by Sukadia** [comment]
no worries at all, mine is just for a bot on discord that whitelists 3 random words every 6 hours- i think the people on there can live without it for a bit haha

**Comment by RazorSh4rk** [comment]
Sorry about this, i left the app run on its own for too long because i expected heroku to be smart and restart crashed dynos, but ut seems like it just doesnt. I upgraded to a hobby dyno for now, but most of the problem comes from a few ${bad_word}s spamming requests, i'll implement a message queue and/or rate limiting asap (and by asap i mean the weekend).

**Comment by RazorSh4rk** [comment]
While i'm getting ddos'ed, please use https://random-word-api2.herokuapp.com , sorry for the inconvenience.

**Comment by sudocode1** [comment]
any updates?

**Comment by RazorSh4rk** [comment]
aaaand we are back, lesson learned from this: heroku's load balancer is nonexistent
